apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: null
  name: xstoragecontainers.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XStorageContainer
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-example-project-azurecompose-container-kcl
    step: compose-container-kcl
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
