# generated by datamodel-codegen:
#   filename:  workdir/storage_azure_upbound_io_v1beta1_account.yaml

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class DeletionPolicy(Enum):
    Orphan = 'Orphan'
    Delete = 'Delete'


class ActiveDirectoryItem(BaseModel):
    domainGuid: Optional[str] = None
    """
    Specifies the domain GUID.
    """
    domainName: Optional[str] = None
    """
    Specifies the primary domain that the AD DNS server is authoritative for.
    """
    domainSid: Optional[str] = None
    """
    Specifies the security identifier (SID). This is required when directory_type is set to AD.
    """
    forestName: Optional[str] = None
    """
    Specifies the Active Directory forest. This is required when directory_type is set to AD.
    """
    netbiosDomainName: Optional[str] = None
    """
    Specifies the NetBIOS domain name. This is required when directory_type is set to AD.
    """
    storageSid: Optional[str] = None
    """
    Specifies the security identifier (SID) for Azure Storage. This is required when directory_type is set to AD.
    """


class AzureFilesAuthenticationItem(BaseModel):
    activeDirectory: Optional[List[ActiveDirectoryItem]] = None
    """
    A active_directory block as defined below. Required when directory_type is AD.
    """
    directoryType: Optional[str] = None
    """
    Specifies the directory service used. Possible values are AADDS, AD and AADKERB.
    """


class ContainerDeleteRetentionPolicyItem(BaseModel):
    days: Optional[float] = None
    """
    Specifies the number of days that the azurerm_storage_share should be retained, between 1 and 365 days. Defaults to 7.
    """


class CorsRuleItem(BaseModel):
    allowedHeaders: Optional[List[str]] = None
    """
    A list of headers that are allowed to be a part of the cross-origin request.
    """
    allowedMethods: Optional[List[str]] = None
    """
    A list of HTTP methods that are allowed to be executed by the origin. Valid options are
    DELETE, GET, HEAD, MERGE, POST, OPTIONS, PUT or PATCH.
    """
    allowedOrigins: Optional[List[str]] = None
    """
    A list of origin domains that will be allowed by CORS.
    """
    exposedHeaders: Optional[List[str]] = None
    """
    A list of response headers that are exposed to CORS clients.
    """
    maxAgeInSeconds: Optional[float] = None
    """
    The number of seconds the client should cache a preflight response.
    """


class DeleteRetentionPolicyItem(BaseModel):
    days: Optional[float] = None
    """
    Specifies the number of days that the azurerm_storage_share should be retained, between 1 and 365 days. Defaults to 7.
    """
    permanentDeleteEnabled: Optional[bool] = None
    """
    Indicates whether permanent deletion of the soft deleted blob versions and snapshots is allowed. Defaults to false.
    """


class RestorePolicyItem(BaseModel):
    days: Optional[float] = None
    """
    Specifies the number of days that the azurerm_storage_share should be retained, between 1 and 365 days. Defaults to 7.
    """


class BlobProperty(BaseModel):
    changeFeedEnabled: Optional[bool] = None
    """
    Is the blob service properties for change feed events enabled? Default to false.
    """
    changeFeedRetentionInDays: Optional[float] = None
    """
    The duration of change feed events retention in days. The possible values are between 1 and 146000 days (400 years). Setting this to null (or omit this in the configuration file) indicates an infinite retention of the change feed.
    """
    containerDeleteRetentionPolicy: Optional[
        List[ContainerDeleteRetentionPolicyItem]
    ] = None
    """
    A container_delete_retention_policy block as defined below.
    """
    corsRule: Optional[List[CorsRuleItem]] = None
    """
    A cors_rule block as defined below.
    """
    defaultServiceVersion: Optional[str] = None
    """
    The API Version which should be used by default for requests to the Data Plane API if an incoming request doesn't specify an API Version.
    """
    deleteRetentionPolicy: Optional[List[DeleteRetentionPolicyItem]] = None
    """
    A delete_retention_policy block as defined below.
    """
    lastAccessTimeEnabled: Optional[bool] = None
    """
    Is the last access time based tracking enabled? Default to false.
    """
    restorePolicy: Optional[List[RestorePolicyItem]] = None
    """
    A restore_policy block as defined below. This must be used together with delete_retention_policy set, versioning_enabled and change_feed_enabled set to true.
    """
    versioningEnabled: Optional[bool] = None
    """
    Is versioning enabled? Default to false.
    """


class CustomDomainItem(BaseModel):
    name: Optional[str] = None
    """
    The Custom Domain Name to use for the Storage Account, which will be validated by Azure.
    """
    useSubdomain: Optional[bool] = None
    """
    Should the Custom Domain Name be validated by using indirect CNAME validation?
    """


class CustomerManagedKeyItem(BaseModel):
    keyVaultKeyId: Optional[str] = None
    """
    The ID of the Key Vault Key, supplying a version-less key ID will enable auto-rotation of this key. Exactly one of key_vault_key_id and managed_hsm_key_id may be specified.
    """
    managedHsmKeyId: Optional[str] = None
    """
    The ID of the managed HSM Key. Exactly one of key_vault_key_id and managed_hsm_key_id may be specified.
    """
    userAssignedIdentityId: Optional[str] = None
    """
    The ID of a user assigned identity.
    """


class IdentityItem(BaseModel):
    identityIds: Optional[List[str]] = None
    """
    Specifies a list of User Assigned Managed Identity IDs to be assigned to this Storage Account.
    """
    type: Optional[str] = None
    """
    Specifies the type of Managed Service Identity that should be configured on this Storage Account. Possible values are SystemAssigned, UserAssigned, SystemAssigned, UserAssigned (to enable both).
    """


class ImmutabilityPolicyItem(BaseModel):
    allowProtectedAppendWrites: Optional[bool] = None
    """
    When enabled, new blocks can be written to an append blob while maintaining immutability protection and compliance. Only new blocks can be added and any existing blocks cannot be modified or deleted.
    """
    periodSinceCreationInDays: Optional[float] = None
    """
    The immutability period for the blobs in the container since the policy creation, in days.
    """
    state: Optional[str] = None
    """
    Defines the mode of the policy. Disabled state disables the policy, Unlocked state allows increase and decrease of immutability retention time and also allows toggling allowProtectedAppendWrites property, Locked state only allows the increase of the immutability retention time. A policy can only be created in a Disabled or Unlocked state and can be toggled between the two states. Only a policy in an Unlocked state can transition to a Locked state which cannot be reverted.
    """


class PrivateLinkAcces(BaseModel):
    endpointResourceId: Optional[str] = None
    """
    The ID of the Azure resource that should be allowed access to the target storage account.
    """
    endpointTenantId: Optional[str] = None
    """
    The tenant id of the resource of the resource access rule to be granted access. Defaults to the current tenant id.
    """


class NetworkRule(BaseModel):
    bypass: Optional[List[str]] = None
    """
    Specifies whether traffic is bypassed for Logging/Metrics/AzureServices. Valid options are any combination of Logging, Metrics, AzureServices, or None.
    """
    defaultAction: Optional[str] = None
    """
    Specifies the default action of allow or deny when no other rules match. Valid options are Deny or Allow.
    """
    ipRules: Optional[List[str]] = None
    """
    List of public IP or IP ranges in CIDR Format. Only IPv4 addresses are allowed. /31 CIDRs, /32 CIDRs, and Private IP address ranges (as defined in RFC 1918), are not allowed.
    """
    privateLinkAccess: Optional[List[PrivateLinkAcces]] = None
    """
    One or more private_link_access block as defined below.
    """
    virtualNetworkSubnetIds: Optional[List[str]] = None
    """
    A list of resource ids for subnets.
    """


class HourMetric(BaseModel):
    enabled: Optional[bool] = None
    """
    Indicates whether minute metrics are enabled for the Queue service.
    """
    includeApis: Optional[bool] = None
    """
    Indicates whether metrics should generate summary statistics for called API operations.
    """
    retentionPolicyDays: Optional[float] = None
    """
    Specifies the number of days that logs will be retained.
    """
    version: Optional[str] = None
    """
    The version of storage analytics to configure.
    """


class LoggingItem(BaseModel):
    delete: Optional[bool] = None
    """
    (Defaults to 60 minutes) Used when deleting the Storage Account.
    """
    read: Optional[bool] = None
    """
    (Defaults to 5 minutes) Used when retrieving the Storage Account.
    """
    retentionPolicyDays: Optional[float] = None
    """
    Specifies the number of days that logs will be retained.
    """
    version: Optional[str] = None
    """
    The version of storage analytics to configure.
    """
    write: Optional[bool] = None
    """
    Indicates whether all write requests should be logged.
    """


class MinuteMetric(BaseModel):
    enabled: Optional[bool] = None
    """
    Indicates whether minute metrics are enabled for the Queue service.
    """
    includeApis: Optional[bool] = None
    """
    Indicates whether metrics should generate summary statistics for called API operations.
    """
    retentionPolicyDays: Optional[float] = None
    """
    Specifies the number of days that logs will be retained.
    """
    version: Optional[str] = None
    """
    The version of storage analytics to configure.
    """


class QueueProperty(BaseModel):
    corsRule: Optional[List[CorsRuleItem]] = None
    """
    A cors_rule block as defined above.
    """
    hourMetrics: Optional[List[HourMetric]] = None
    """
    A hour_metrics block as defined below.
    """
    logging: Optional[List[LoggingItem]] = None
    """
    A logging block as defined below.
    """
    minuteMetrics: Optional[List[MinuteMetric]] = None
    """
    A minute_metrics block as defined below.
    """


class Resolution(Enum):
    Required = 'Required'
    Optional = 'Optional'


class Resolve(Enum):
    Always = 'Always'
    IfNotPresent = 'IfNotPresent'


class Policy(BaseModel):
    resolution: Optional[Resolution] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Resolve] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ResourceGroupNameRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class ResourceGroupNameSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class RoutingItem(BaseModel):
    choice: Optional[str] = None
    """
    Specifies the kind of network routing opted by the user. Possible values are InternetRouting and MicrosoftRouting. Defaults to MicrosoftRouting.
    """
    publishInternetEndpoints: Optional[bool] = None
    """
    Should internet routing storage endpoints be published? Defaults to false.
    """
    publishMicrosoftEndpoints: Optional[bool] = None
    """
    Should Microsoft routing storage endpoints be published? Defaults to false.
    """


class SasPolicyItem(BaseModel):
    expirationAction: Optional[str] = None
    """
    The SAS expiration action. The only possible value is Log at this moment. Defaults to Log.
    """
    expirationPeriod: Optional[str] = None
    """
    The SAS expiration period in format of DD.HH:MM:SS.
    """


class RetentionPolicyItem(BaseModel):
    days: Optional[float] = None
    """
    Specifies the number of days that the azurerm_storage_share should be retained, between 1 and 365 days. Defaults to 7.
    """


class SmbItem(BaseModel):
    authenticationTypes: Optional[List[str]] = None
    """
    A set of SMB authentication methods. Possible values are NTLMv2, and Kerberos.
    """
    channelEncryptionType: Optional[List[str]] = None
    """
    A set of SMB channel encryption. Possible values are AES-128-CCM, AES-128-GCM, and AES-256-GCM.
    """
    kerberosTicketEncryptionType: Optional[List[str]] = None
    """
    A set of Kerberos ticket encryption. Possible values are RC4-HMAC, and AES-256.
    """
    multichannelEnabled: Optional[bool] = None
    """
    Indicates whether multichannel is enabled. Defaults to false. This is only supported on Premium storage accounts.
    """
    versions: Optional[List[str]] = None
    """
    A set of SMB protocol versions. Possible values are SMB2.1, SMB3.0, and SMB3.1.1.
    """


class ShareProperty(BaseModel):
    corsRule: Optional[List[CorsRuleItem]] = None
    """
    A cors_rule block as defined below.
    """
    retentionPolicy: Optional[List[RetentionPolicyItem]] = None
    """
    A retention_policy block as defined below.
    """
    smb: Optional[List[SmbItem]] = None
    """
    A smb block as defined below.
    """


class StaticWebsiteItem(BaseModel):
    error404Document: Optional[str] = None
    """
    The absolute path to a custom webpage that should be used when a request is made which does not correspond to an existing file.
    """
    indexDocument: Optional[str] = None
    """
    The webpage that Azure Storage serves for requests to the root of a website or any subfolder. For example, index.html. The value is case-sensitive.
    """


class ForProvider(BaseModel):
    accessTier: Optional[str] = None
    """
    Defines the access tier for BlobStorage, FileStorage and StorageV2 accounts. Valid options are Hot and Cool, defaults to Hot.
    """
    accountKind: Optional[str] = None
    """
    Defines the Kind of account. Valid options are BlobStorage, BlockBlobStorage, FileStorage, Storage and StorageV2. Defaults to StorageV2.
    """
    accountReplicationType: Optional[str] = None
    """
    Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS. Changing this forces a new resource to be created when types LRS, GRS and RAGRS are changed to ZRS, GZRS or RAGZRS and vice versa.
    """
    accountTier: Optional[str] = None
    """
    Defines the Tier to use for this storage account. Valid options are Standard and Premium. For BlockBlobStorage and FileStorage accounts only Premium is valid. Changing this forces a new resource to be created.
    """
    allowNestedItemsToBePublic: Optional[bool] = None
    """
    Allow or disallow nested items within this Account to opt into being public. Defaults to true.
    """
    allowedCopyScope: Optional[str] = None
    """
    Restrict copy to and from Storage Accounts within an AAD tenant or with Private Links to the same VNet. Possible values are AAD and PrivateLink.
    """
    azureFilesAuthentication: Optional[List[AzureFilesAuthenticationItem]] = None
    """
    A azure_files_authentication block as defined below.
    """
    blobProperties: Optional[List[BlobProperty]] = None
    """
    A blob_properties block as defined below.
    """
    crossTenantReplicationEnabled: Optional[bool] = None
    """
    Should cross Tenant replication be enabled? Defaults to true.
    """
    customDomain: Optional[List[CustomDomainItem]] = None
    """
    A custom_domain block as documented below.
    """
    customerManagedKey: Optional[List[CustomerManagedKeyItem]] = None
    """
    A customer_managed_key block as documented below.
    """
    defaultToOauthAuthentication: Optional[bool] = None
    """
    Default to Azure Active Directory authorization in the Azure portal when accessing the Storage Account. The default value is false
    """
    dnsEndpointType: Optional[str] = None
    """
    Specifies which DNS endpoint type to use. Possible values are Standard and AzureDnsZone. Defaults to Standard. Changing this forces a new resource to be created.
    """
    edgeZone: Optional[str] = None
    """
    Specifies the Edge Zone within the Azure Region where this Storage Account should exist. Changing this forces a new Storage Account to be created.
    """
    enableHttpsTrafficOnly: Optional[bool] = None
    """
    Boolean flag which forces HTTPS if enabled, see here for more information. Defaults to true.
    """
    identity: Optional[List[IdentityItem]] = None
    """
    An identity block as defined below.
    """
    immutabilityPolicy: Optional[List[ImmutabilityPolicyItem]] = None
    """
    An immutability_policy block as defined below. Changing this forces a new resource to be created.
    """
    infrastructureEncryptionEnabled: Optional[bool] = None
    """
    Is infrastructure encryption enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    isHnsEnabled: Optional[bool] = None
    """
    Is Hierarchical Namespace enabled? This can be used with Azure Data Lake Storage Gen 2 (see here for more information). Changing this forces a new resource to be created.
    """
    largeFileShareEnabled: Optional[bool] = None
    """
    Is Large File Share Enabled?
    """
    localUserEnabled: Optional[bool] = None
    """
    Is Local User Enabled? Defaults to true.
    """
    location: Optional[str] = None
    """
    Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
    """
    minTlsVersion: Optional[str] = None
    """
    The minimum supported TLS version for the storage account. Possible values are TLS1_0, TLS1_1, and TLS1_2. Defaults to TLS1_2 for new storage accounts.
    """
    networkRules: Optional[List[NetworkRule]] = None
    """
    A network_rules block as documented below.
    """
    nfsv3Enabled: Optional[bool] = None
    """
    Is NFSv3 protocol enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    publicNetworkAccessEnabled: Optional[bool] = None
    """
    Whether the public network access is enabled? Defaults to true.
    """
    queueEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the queue service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    queueProperties: Optional[List[QueueProperty]] = None
    """
    A queue_properties block as defined below.
    """
    resourceGroupName: Optional[str] = None
    """
    The name of the resource group in which to create the storage account. Changing this forces a new resource to be created.
    """
    resourceGroupNameRef: Optional[ResourceGroupNameRef] = None
    """
    Reference to a ResourceGroup in azure to populate resourceGroupName.
    """
    resourceGroupNameSelector: Optional[ResourceGroupNameSelector] = None
    """
    Selector for a ResourceGroup in azure to populate resourceGroupName.
    """
    routing: Optional[List[RoutingItem]] = None
    """
    A routing block as defined below.
    """
    sasPolicy: Optional[List[SasPolicyItem]] = None
    """
    A sas_policy block as defined below.
    """
    sftpEnabled: Optional[bool] = None
    """
    Boolean, enable SFTP for the storage account
    """
    shareProperties: Optional[List[ShareProperty]] = None
    """
    A share_properties block as defined below.
    """
    sharedAccessKeyEnabled: Optional[bool] = None
    """
    Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). Defaults to true.
    """
    staticWebsite: Optional[List[StaticWebsiteItem]] = None
    """
    A static_website block as defined below.
    """
    tableEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the table service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    tags: Optional[Dict[str, str]] = None
    """
    A mapping of tags to assign to the resource.
    """


class InitProvider(BaseModel):
    accessTier: Optional[str] = None
    """
    Defines the access tier for BlobStorage, FileStorage and StorageV2 accounts. Valid options are Hot and Cool, defaults to Hot.
    """
    accountKind: Optional[str] = None
    """
    Defines the Kind of account. Valid options are BlobStorage, BlockBlobStorage, FileStorage, Storage and StorageV2. Defaults to StorageV2.
    """
    accountReplicationType: Optional[str] = None
    """
    Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS. Changing this forces a new resource to be created when types LRS, GRS and RAGRS are changed to ZRS, GZRS or RAGZRS and vice versa.
    """
    accountTier: Optional[str] = None
    """
    Defines the Tier to use for this storage account. Valid options are Standard and Premium. For BlockBlobStorage and FileStorage accounts only Premium is valid. Changing this forces a new resource to be created.
    """
    allowNestedItemsToBePublic: Optional[bool] = None
    """
    Allow or disallow nested items within this Account to opt into being public. Defaults to true.
    """
    allowedCopyScope: Optional[str] = None
    """
    Restrict copy to and from Storage Accounts within an AAD tenant or with Private Links to the same VNet. Possible values are AAD and PrivateLink.
    """
    azureFilesAuthentication: Optional[List[AzureFilesAuthenticationItem]] = None
    """
    A azure_files_authentication block as defined below.
    """
    blobProperties: Optional[List[BlobProperty]] = None
    """
    A blob_properties block as defined below.
    """
    crossTenantReplicationEnabled: Optional[bool] = None
    """
    Should cross Tenant replication be enabled? Defaults to true.
    """
    customDomain: Optional[List[CustomDomainItem]] = None
    """
    A custom_domain block as documented below.
    """
    customerManagedKey: Optional[List[CustomerManagedKeyItem]] = None
    """
    A customer_managed_key block as documented below.
    """
    defaultToOauthAuthentication: Optional[bool] = None
    """
    Default to Azure Active Directory authorization in the Azure portal when accessing the Storage Account. The default value is false
    """
    dnsEndpointType: Optional[str] = None
    """
    Specifies which DNS endpoint type to use. Possible values are Standard and AzureDnsZone. Defaults to Standard. Changing this forces a new resource to be created.
    """
    edgeZone: Optional[str] = None
    """
    Specifies the Edge Zone within the Azure Region where this Storage Account should exist. Changing this forces a new Storage Account to be created.
    """
    enableHttpsTrafficOnly: Optional[bool] = None
    """
    Boolean flag which forces HTTPS if enabled, see here for more information. Defaults to true.
    """
    identity: Optional[List[IdentityItem]] = None
    """
    An identity block as defined below.
    """
    immutabilityPolicy: Optional[List[ImmutabilityPolicyItem]] = None
    """
    An immutability_policy block as defined below. Changing this forces a new resource to be created.
    """
    infrastructureEncryptionEnabled: Optional[bool] = None
    """
    Is infrastructure encryption enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    isHnsEnabled: Optional[bool] = None
    """
    Is Hierarchical Namespace enabled? This can be used with Azure Data Lake Storage Gen 2 (see here for more information). Changing this forces a new resource to be created.
    """
    largeFileShareEnabled: Optional[bool] = None
    """
    Is Large File Share Enabled?
    """
    localUserEnabled: Optional[bool] = None
    """
    Is Local User Enabled? Defaults to true.
    """
    location: Optional[str] = None
    """
    Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
    """
    minTlsVersion: Optional[str] = None
    """
    The minimum supported TLS version for the storage account. Possible values are TLS1_0, TLS1_1, and TLS1_2. Defaults to TLS1_2 for new storage accounts.
    """
    networkRules: Optional[List[NetworkRule]] = None
    """
    A network_rules block as documented below.
    """
    nfsv3Enabled: Optional[bool] = None
    """
    Is NFSv3 protocol enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    publicNetworkAccessEnabled: Optional[bool] = None
    """
    Whether the public network access is enabled? Defaults to true.
    """
    queueEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the queue service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    queueProperties: Optional[List[QueueProperty]] = None
    """
    A queue_properties block as defined below.
    """
    routing: Optional[List[RoutingItem]] = None
    """
    A routing block as defined below.
    """
    sasPolicy: Optional[List[SasPolicyItem]] = None
    """
    A sas_policy block as defined below.
    """
    sftpEnabled: Optional[bool] = None
    """
    Boolean, enable SFTP for the storage account
    """
    shareProperties: Optional[List[ShareProperty]] = None
    """
    A share_properties block as defined below.
    """
    sharedAccessKeyEnabled: Optional[bool] = None
    """
    Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). Defaults to true.
    """
    staticWebsite: Optional[List[StaticWebsiteItem]] = None
    """
    A static_website block as defined below.
    """
    tableEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the table service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    tags: Optional[Dict[str, str]] = None
    """
    A mapping of tags to assign to the resource.
    """


class ManagementPolicy(Enum):
    Observe = 'Observe'
    Create = 'Create'
    Update = 'Update'
    Delete = 'Delete'
    LateInitialize = 'LateInitialize'
    field_ = '*'


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class ConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class Metadata(BaseModel):
    annotations: Optional[Dict[str, str]] = None
    """
    Annotations are the annotations to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.annotations".
    - It is up to Secret Store implementation for others store types.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels are the labels/tags to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.labels".
    - It is up to Secret Store implementation for others store types.
    """
    type: Optional[str] = None
    """
    Type is the SecretType for the connection secret.
    - Only valid for Kubernetes Secret Stores.
    """


class PublishConnectionDetailsTo(BaseModel):
    configRef: Optional[ConfigRef] = Field(
        default_factory=lambda: ConfigRef.model_validate({'name': 'default'})
    )
    """
    SecretStoreConfigRef specifies which secret store config should be used
    for this ConnectionSecret.
    """
    metadata: Optional[Metadata] = None
    """
    Metadata is the metadata for connection secret.
    """
    name: str
    """
    Name is the name of the connection secret.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[DeletionPolicy] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[List[ManagementPolicy]] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    publishConnectionDetailsTo: Optional[PublishConnectionDetailsTo] = None
    """
    PublishConnectionDetailsTo specifies the connection secret config which
    contains a name, metadata and a reference to secret store config to
    which any connection details for this managed resource should be written.
    Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    This field is planned to be replaced in a future release in favor of
    PublishConnectionDetailsTo. Currently, both could be set independently
    and connection details would be published to both without affecting
    each other.
    """


class IdentityItemModel(BaseModel):
    identityIds: Optional[List[str]] = None
    """
    Specifies a list of User Assigned Managed Identity IDs to be assigned to this Storage Account.
    """
    principalId: Optional[str] = None
    """
    The Principal ID for the Service Principal associated with the Identity of this Storage Account.
    """
    tenantId: Optional[str] = None
    """
    The Tenant ID for the Service Principal associated with the Identity of this Storage Account.
    """
    type: Optional[str] = None
    """
    Specifies the type of Managed Service Identity that should be configured on this Storage Account. Possible values are SystemAssigned, UserAssigned, SystemAssigned, UserAssigned (to enable both).
    """


class AtProvider(BaseModel):
    accessTier: Optional[str] = None
    """
    Defines the access tier for BlobStorage, FileStorage and StorageV2 accounts. Valid options are Hot and Cool, defaults to Hot.
    """
    accountKind: Optional[str] = None
    """
    Defines the Kind of account. Valid options are BlobStorage, BlockBlobStorage, FileStorage, Storage and StorageV2. Defaults to StorageV2.
    """
    accountReplicationType: Optional[str] = None
    """
    Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS. Changing this forces a new resource to be created when types LRS, GRS and RAGRS are changed to ZRS, GZRS or RAGZRS and vice versa.
    """
    accountTier: Optional[str] = None
    """
    Defines the Tier to use for this storage account. Valid options are Standard and Premium. For BlockBlobStorage and FileStorage accounts only Premium is valid. Changing this forces a new resource to be created.
    """
    allowNestedItemsToBePublic: Optional[bool] = None
    """
    Allow or disallow nested items within this Account to opt into being public. Defaults to true.
    """
    allowedCopyScope: Optional[str] = None
    """
    Restrict copy to and from Storage Accounts within an AAD tenant or with Private Links to the same VNet. Possible values are AAD and PrivateLink.
    """
    azureFilesAuthentication: Optional[List[AzureFilesAuthenticationItem]] = None
    """
    A azure_files_authentication block as defined below.
    """
    blobProperties: Optional[List[BlobProperty]] = None
    """
    A blob_properties block as defined below.
    """
    crossTenantReplicationEnabled: Optional[bool] = None
    """
    Should cross Tenant replication be enabled? Defaults to true.
    """
    customDomain: Optional[List[CustomDomainItem]] = None
    """
    A custom_domain block as documented below.
    """
    customerManagedKey: Optional[List[CustomerManagedKeyItem]] = None
    """
    A customer_managed_key block as documented below.
    """
    defaultToOauthAuthentication: Optional[bool] = None
    """
    Default to Azure Active Directory authorization in the Azure portal when accessing the Storage Account. The default value is false
    """
    dnsEndpointType: Optional[str] = None
    """
    Specifies which DNS endpoint type to use. Possible values are Standard and AzureDnsZone. Defaults to Standard. Changing this forces a new resource to be created.
    """
    edgeZone: Optional[str] = None
    """
    Specifies the Edge Zone within the Azure Region where this Storage Account should exist. Changing this forces a new Storage Account to be created.
    """
    enableHttpsTrafficOnly: Optional[bool] = None
    """
    Boolean flag which forces HTTPS if enabled, see here for more information. Defaults to true.
    """
    id: Optional[str] = None
    """
    The ID of the Storage Account.
    """
    identity: Optional[List[IdentityItemModel]] = None
    """
    An identity block as defined below.
    """
    immutabilityPolicy: Optional[List[ImmutabilityPolicyItem]] = None
    """
    An immutability_policy block as defined below. Changing this forces a new resource to be created.
    """
    infrastructureEncryptionEnabled: Optional[bool] = None
    """
    Is infrastructure encryption enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    isHnsEnabled: Optional[bool] = None
    """
    Is Hierarchical Namespace enabled? This can be used with Azure Data Lake Storage Gen 2 (see here for more information). Changing this forces a new resource to be created.
    """
    largeFileShareEnabled: Optional[bool] = None
    """
    Is Large File Share Enabled?
    """
    localUserEnabled: Optional[bool] = None
    """
    Is Local User Enabled? Defaults to true.
    """
    location: Optional[str] = None
    """
    Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
    """
    minTlsVersion: Optional[str] = None
    """
    The minimum supported TLS version for the storage account. Possible values are TLS1_0, TLS1_1, and TLS1_2. Defaults to TLS1_2 for new storage accounts.
    """
    networkRules: Optional[List[NetworkRule]] = None
    """
    A network_rules block as documented below.
    """
    nfsv3Enabled: Optional[bool] = None
    """
    Is NFSv3 protocol enabled? Changing this forces a new resource to be created. Defaults to false.
    """
    primaryBlobEndpoint: Optional[str] = None
    """
    The endpoint URL for blob storage in the primary location.
    """
    primaryBlobHost: Optional[str] = None
    """
    The hostname with port if applicable for blob storage in the primary location.
    """
    primaryBlobInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for blob storage in the primary location.
    """
    primaryBlobInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for blob storage in the primary location.
    """
    primaryBlobMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for blob storage in the primary location.
    """
    primaryBlobMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for blob storage in the primary location.
    """
    primaryDfsEndpoint: Optional[str] = None
    """
    The endpoint URL for DFS storage in the primary location.
    """
    primaryDfsHost: Optional[str] = None
    """
    The hostname with port if applicable for DFS storage in the primary location.
    """
    primaryDfsInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for DFS storage in the primary location.
    """
    primaryDfsInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for DFS storage in the primary location.
    """
    primaryDfsMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for DFS storage in the primary location.
    """
    primaryDfsMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for DFS storage in the primary location.
    """
    primaryFileEndpoint: Optional[str] = None
    """
    The endpoint URL for file storage in the primary location.
    """
    primaryFileHost: Optional[str] = None
    """
    The hostname with port if applicable for file storage in the primary location.
    """
    primaryFileInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for file storage in the primary location.
    """
    primaryFileInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for file storage in the primary location.
    """
    primaryFileMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for file storage in the primary location.
    """
    primaryFileMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for file storage in the primary location.
    """
    primaryLocation: Optional[str] = None
    """
    The primary location of the storage account.
    """
    primaryQueueEndpoint: Optional[str] = None
    """
    The endpoint URL for queue storage in the primary location.
    """
    primaryQueueHost: Optional[str] = None
    """
    The hostname with port if applicable for queue storage in the primary location.
    """
    primaryQueueMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for queue storage in the primary location.
    """
    primaryQueueMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for queue storage in the primary location.
    """
    primaryTableEndpoint: Optional[str] = None
    """
    The endpoint URL for table storage in the primary location.
    """
    primaryTableHost: Optional[str] = None
    """
    The hostname with port if applicable for table storage in the primary location.
    """
    primaryTableMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for table storage in the primary location.
    """
    primaryTableMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for table storage in the primary location.
    """
    primaryWebEndpoint: Optional[str] = None
    """
    The endpoint URL for web storage in the primary location.
    """
    primaryWebHost: Optional[str] = None
    """
    The hostname with port if applicable for web storage in the primary location.
    """
    primaryWebInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for web storage in the primary location.
    """
    primaryWebInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for web storage in the primary location.
    """
    primaryWebMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for web storage in the primary location.
    """
    primaryWebMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for web storage in the primary location.
    """
    publicNetworkAccessEnabled: Optional[bool] = None
    """
    Whether the public network access is enabled? Defaults to true.
    """
    queueEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the queue service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    queueProperties: Optional[List[QueueProperty]] = None
    """
    A queue_properties block as defined below.
    """
    resourceGroupName: Optional[str] = None
    """
    The name of the resource group in which to create the storage account. Changing this forces a new resource to be created.
    """
    routing: Optional[List[RoutingItem]] = None
    """
    A routing block as defined below.
    """
    sasPolicy: Optional[List[SasPolicyItem]] = None
    """
    A sas_policy block as defined below.
    """
    secondaryBlobEndpoint: Optional[str] = None
    """
    The endpoint URL for blob storage in the secondary location.
    """
    secondaryBlobHost: Optional[str] = None
    """
    The hostname with port if applicable for blob storage in the secondary location.
    """
    secondaryBlobInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for blob storage in the secondary location.
    """
    secondaryBlobInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for blob storage in the secondary location.
    """
    secondaryBlobMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for blob storage in the secondary location.
    """
    secondaryBlobMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for blob storage in the secondary location.
    """
    secondaryDfsEndpoint: Optional[str] = None
    """
    The endpoint URL for DFS storage in the secondary location.
    """
    secondaryDfsHost: Optional[str] = None
    """
    The hostname with port if applicable for DFS storage in the secondary location.
    """
    secondaryDfsInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for DFS storage in the secondary location.
    """
    secondaryDfsInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for DFS storage in the secondary location.
    """
    secondaryDfsMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for DFS storage in the secondary location.
    """
    secondaryDfsMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for DFS storage in the secondary location.
    """
    secondaryFileEndpoint: Optional[str] = None
    """
    The endpoint URL for file storage in the secondary location.
    """
    secondaryFileHost: Optional[str] = None
    """
    The hostname with port if applicable for file storage in the secondary location.
    """
    secondaryFileInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for file storage in the secondary location.
    """
    secondaryFileInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for file storage in the secondary location.
    """
    secondaryFileMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for file storage in the secondary location.
    """
    secondaryFileMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for file storage in the secondary location.
    """
    secondaryLocation: Optional[str] = None
    """
    The secondary location of the storage account.
    """
    secondaryQueueEndpoint: Optional[str] = None
    """
    The endpoint URL for queue storage in the secondary location.
    """
    secondaryQueueHost: Optional[str] = None
    """
    The hostname with port if applicable for queue storage in the secondary location.
    """
    secondaryQueueMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for queue storage in the secondary location.
    """
    secondaryQueueMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for queue storage in the secondary location.
    """
    secondaryTableEndpoint: Optional[str] = None
    """
    The endpoint URL for table storage in the secondary location.
    """
    secondaryTableHost: Optional[str] = None
    """
    The hostname with port if applicable for table storage in the secondary location.
    """
    secondaryTableMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for table storage in the secondary location.
    """
    secondaryTableMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for table storage in the secondary location.
    """
    secondaryWebEndpoint: Optional[str] = None
    """
    The endpoint URL for web storage in the secondary location.
    """
    secondaryWebHost: Optional[str] = None
    """
    The hostname with port if applicable for web storage in the secondary location.
    """
    secondaryWebInternetEndpoint: Optional[str] = None
    """
    The internet routing endpoint URL for web storage in the secondary location.
    """
    secondaryWebInternetHost: Optional[str] = None
    """
    The internet routing hostname with port if applicable for web storage in the secondary location.
    """
    secondaryWebMicrosoftEndpoint: Optional[str] = None
    """
    The microsoft routing endpoint URL for web storage in the secondary location.
    """
    secondaryWebMicrosoftHost: Optional[str] = None
    """
    The microsoft routing hostname with port if applicable for web storage in the secondary location.
    """
    sftpEnabled: Optional[bool] = None
    """
    Boolean, enable SFTP for the storage account
    """
    shareProperties: Optional[List[ShareProperty]] = None
    """
    A share_properties block as defined below.
    """
    sharedAccessKeyEnabled: Optional[bool] = None
    """
    Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). Defaults to true.
    """
    staticWebsite: Optional[List[StaticWebsiteItem]] = None
    """
    A static_website block as defined below.
    """
    tableEncryptionKeyType: Optional[str] = None
    """
    The encryption type of the table service. Possible values are Service and Account. Changing this forces a new resource to be created. Default value is Service.
    """
    tags: Optional[Dict[str, str]] = None
    """
    A mapping of tags to assign to the resource.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Account(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    AccountSpec defines the desired state of Account
    """
    status: Optional[Status] = None
    """
    AccountStatus defines the observed state of Account.
    """


class AccountList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[Account]
    """
    List of accounts. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """